<?php
/**
 * Rin News
 * https://github.com/martec
 *
 * Copyright (C) 2015-2015, Martec
 *
 * Rin News is licensed under the GPL Version 3, 29 June 2007 license:
 *	http://www.gnu.org/copyleft/gpl.html
 *
 * @fileoverview Rin News - Firebase News for Mybb
 * @author Martec
 * @requires jQuery, Firebase and Mybb
 * @credits notify.png icon from http://community.mybb.com/post-861176.html
 * @credits some part of code based in MyAlerts of Euan T (http://community.mybb.com/thread-127444.html)
 */

$l['rinnews_plug_desc'] = 'Firebase News for Mybb.';
$l['rinnews_sett_desc'] = 'Settings for the Rin News.';
$l['rinnews_onoff_title'] = 'Enable Rin News?';
$l['rinnews_onoff_desc'] = 'Set here if you want enable or disable Rin News.';
$l['rinnews_newslimit_title'] = 'Amount of news';
$l['rinnews_newslimit_desc'] = 'Set here amount of news that will appear.';
$l['rinnews_newsmyalimit_title'] = 'Amount of Myalerts news';
$l['rinnews_newsmyalimit_desc'] = 'Set here amount of news generated by Myalerts that will appear.';
$l['rinnews_nogrp_title'] = 'Group without permission to use';
$l['rinnews_nogrp_desc'] = 'Set here group that does not has permission to use Rin News.';
$l['rinnews_apikey_title'] = 'Your Firebase API Key';
$l['rinnews_apikey_desc'] = 'Set here Firebase API Key.';
$l['rinnews_authdomain_title'] = 'Your Firebase Authentication Domain';
$l['rinnews_authdomain_desc'] = 'Set here Firebase Authentication Domain.';
$l['rinnews_databaseurl_title'] = 'Your Firebase Database URL';
$l['rinnews_databaseurl_desc'] = 'Set here Firebase Database URL.';
$l['rinnews_clientemail_title'] = 'Your Firebase Client Email';
$l['rinnews_clientemail_desc'] = 'Set here Firebase Client Email.';
$l['rinnews_privatekey_title'] = 'Your Firebase Private Key';
$l['rinnews_privatekey_desc'] = 'Set here Firebase Private Key.';
$l['rinnews_fsecret_title'] = 'Your Firebase Secret';
$l['rinnews_fsecret_desc'] = 'Set here Firebase Secret.';
$l['rinnews_newpost_title'] = 'New post';
$l['rinnews_newpost_desc'] = 'Show news alert when someone post in thread.';
$l['rinnews_newthread_title'] = 'New thread';
$l['rinnews_newthread_desc'] = 'Show news alert when someone post new thread.';
$l['rinnews_foldacc_title'] = 'Folder ignored by new post and new thread';
$l['rinnews_foldacc_desc'] = 'Set here folder that Rin News will ignore when someone post in forum (value in id).<br />Separate each forum id with comma.';
$l['rinnews_newpost_lang'] = 'posted in thread {1}';
$l['rinnews_newthread_lang'] = 'posted new thread {1}';
$l['rinnews_dataf_title'] = 'Date Format';
$l['rinnews_dataf_desc'] = 'Set here date format (Options of format you can check in http://momentjs.com/docs/).';
$l['rinnews_newpostcolor_title'] = 'New Post Color';
$l['rinnews_newpostcolor_desc'] = 'Set here color used by Rin News for New Post';
$l['rinnews_newthreadcolor_title'] = 'New Thread Color';
$l['rinnews_newthreadcolor_desc'] = 'Set here color used by Rin News for New Thread';
$l['rinnews_myalertscolor_title'] = 'New Myalerts Color';
$l['rinnews_myalertscolor_desc'] = 'Set here color used by Rin News for New Myalerts alert';
$l['rinnews_myalertonoff_title'] = 'Myalert support';
$l['rinnews_myalertonoff_desc'] = 'Set here if you want enable myalert support. This feature require myalert installed and myalerts.php edited.';
$l['rinnews_usefsockopen_title'] = 'Use fsockopen instead of curl?';
$l['rinnews_usefsockopen_desc'] = 'Set here you want active fsockopen instead of curl. If you select yes, Rin News will use fsockopen.';
?>